name: user_repository
description: The repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  cloud_firestore: ^5.3.0
  equatable: ^2.0.5
  firebase_auth: ^5.2.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
