name: firebase_auth_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
